### ISSUE TITLE
Contribution back to Spring Integration

### ISSUE THREAD

**Issue by artembilan** [xpadro/spring-integration#1]
Hello @xpadro !

I'm very impressed with this your repository and those blog post promoting Spring Integration and its progress the last time. :smile: 

How about to contribute your samples back to the native Spring Integration Samples [repository](https://github.com/spring-projects/spring-integration-samples) ?

Thank you very for such a valuable work!

Regards,
Artem Bilan
Spring Integration team

**Comment by xpadro** [comment]
Hello Artem,

Thank you for valuating my work, I really appreciate it!

Regarding contributing to the Spring repository, I am sending you an email to talk about it.

Regards,
Xavi

**Comment by artembilan** [comment]
Fixed as https://github.com/spring-projects/spring-integration-samples/commit/f4b48a6cc13b5f789571436b9bd3ac87af001f21.

Plus see the link from the `Community Sample Projects` category on the main Spring Integration page: http://projects.spring.io/spring-integration/

Thank you for your valuable contribution!

Looking forward for more! :smile: 

P.S. Don't hesitate to contribute back to the original project, not only samples :wink:
