### ISSUE TITLE
InfrastructureConfiguration.java - httpPostPutFlow() - Unreachable code

### ISSUE THREAD

**Issue by esikgabi** [xpadro/spring-integration#3]
Hi Xavier,

Your spring integration samples are really great. I've tried build the http-dsl project, but the build was failed: "spring-integration/http/http-dsl/src/main/java/xpadro/spring/integration/server/configuration/InfrastructureConfiguration.java:[34,17] unreachable statement"

Why does the httpPostPutFlow start "return null"?
If I remove it, the warning is gone and the build is successfull.

Thanks,
Gabor

**Comment by xpadro** [comment]
I removed this invalid "return null" statement since it was obviously wrong.

Thank you Gabor for spotting this issue :)
